FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

ARG NEXT_PUBLIC_HEDERA_NETWORK
ARG NEXT_PUBLIC_PINATA_GATEWAY
ARG NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
ARG NEXT_PUBLIC_VRS_TOKEN_ID
ARG NEXT_PUBLIC_REGISTRY_TOPIC_ID
ARG NEXT_PUBLIC_QUESTIONS_TOPIC_ID
ARG NEXT_PUBLIC_UPDATES_TOPIC_ID
ARG NEXT_PUBLIC_BOUNTY_CONTRACT_ID
ARG NEXT_PUBLIC_SWAP_CONTRACT_ID
ARG NEXT_PUBLIC_OPERATOR_ACCOUNT_ID
ARG NEXT_PUBLIC_ANNOUNCEMENTS_TOPIC_ID
ARG NEXT_PUBLIC_REVALIDATION_SECRET

RUN pnpm build

EXPOSE 3000

ENV NODE_ENV=production
ENV PORT=3000
ENV NEXT_TELEMETRY_DISABLED=1

CMD ["sh", "-c", "pnpm start -p ${PORT}"]
